
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="another_furniture"
version="1.0.1"
displayName="Another Furniture Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="mod_icon.png"
credits=""
authors="crispytwig, Synthestra"
description='''Another Furniture Mod aims to add furniture, like many other mods, with a goal of staying vanilla-styled and consistently sized, keeping normal blocks and player sizes in mind.'''

[[dependencies.another_furniture]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.another_furniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
