
modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="another_furniture"
version="${file.jarVersion}"
displayName="Example Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
credits=""
authors="crispytwig, Synthestra"
description='''
Furniture.
Mod.
'''

[[dependencies.another_furniture]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.another_furniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
