
modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="another_furniture"
version="1.0.2"
displayName="Another Furniture Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/another-furniture"
issueTrackerURL="https://github.com/crispytwig/Another-Furniture-Mod/issues"
logoFile="mod_icon.png"
credits=""
authors="crispytwig, Synthestra"
description='''Another Furniture Mod aims to add furniture, like many other mods, with a goal of staying vanilla-styled and consistently sized, keeping normal blocks and player sizes in mind.'''

[[dependencies.another_furniture]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.another_furniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
